import { Injectable } from '@angular/core';
import { Product } from './product.model';

@Injectable({ providedIn: 'root' })
export class ProductService {
  private products: Product[] = [
    {
      id: 1,
      category: 'RADIANCE',
      name: 'Brightening Serum Cream',
      image: 'assets/imgs/product-img-1.png',
      oldPrice: 200,
      price: 176,
      rating: 5,
      reviewsCount: 50,
      isNew: true,
      outOfStock: true,
    },
    {
      id: 2,
      category: 'RADIANT',
      name: 'Hydrating Red Lip Stain',
      image: 'assets/imgs/product-img-2.png',
      oldPrice: 200,
      price: 187,
      rating: 5,
      reviewsCount: 50,
      isNew: true,
    },
    {
      id: 3,
      category: 'CRYSTAL',
      name: 'Prism Eyeshadow Palette',
      image: 'assets/imgs/product-img-3.png',
      oldPrice: 200,
      price: 170,
      rating: 5,
      reviewsCount: 50,
      discount: 15,
    },
    {
      id: 4,
      category: 'CRYSTAL GLEAM',
      name: 'Crystal-Infused Highlighter',
      image: 'assets/imgs/product-img-4.png',
      oldPrice: 200,
      price: 150,
      rating: 5,
      reviewsCount: 50,
      isHot: true,
      discount: 15,
      sizes: ['1500 ML', '1000 ML', '500 ML', '250 ML'],
    },
    {
      id: 5,
      category: 'VELVET',
      name: 'Velvet Matte Lipstick',
      image: 'assets/imgs/product-img-5.png',
      oldPrice: 180,
      price: 130,
      rating: 4,
      reviewsCount: 38,
      isNew: true,
      discount: 10,
    },
    {
      id: 6,
      category: 'GLOW',
      name: 'Golden Hour Face Oil',
      image: 'assets/imgs/product-img-6.png',
      oldPrice: 250,
      price: 199,
      rating: 5,
      reviewsCount: 72,
      isHot: true,
    },
    {
      id: 7,
      category: 'RADIANCE',
      name: 'Rose Quartz Face Mask',
      image: 'assets/imgs/product-img-7.png',
      oldPrice: 150,
      price: 120,
      rating: 4,
      reviewsCount: 29,
      discount: 20,
    },
    {
      id: 8,
      category: 'CRYSTAL',
      name: 'Shimmer Body Lotion',
      image: 'assets/imgs/product-img-8.png',
      oldPrice: 160,
      price: 140,
      rating: 5,
      reviewsCount: 45,
    },
    {
      id: 9,
      category: 'VELVET',
      name: 'Satin Foundation SPF 30',
      image: 'assets/imgs/product-img-9.png',
      oldPrice: 300,
      price: 240,
      rating: 4,
      reviewsCount: 61,
      isNew: true,
    },
    {
      id: 10,
      category: 'GLOW',
      name: 'Pearl Luminizer Drops',
      image: 'assets/imgs/product-img-11.png',
      oldPrice: 190,
      price: 155,
      rating: 5,
      reviewsCount: 83,
      isHot: true,
      discount: 18,
    },
    {
      id: 11,
      category: 'RADIANT',
      name: 'Berry Blush Cheek Tint',
      image: 'assets/imgs/product-img-12.png',
      oldPrice: 130,
      price: 99,
      rating: 4,
      reviewsCount: 34,
      discount: 24,
    },
    {
      id: 12,
      category: 'CRYSTAL GLEAM',
      name: 'Diamond Dust Setting Powder',
      image: 'assets/imgs/product-img-1.png',
      oldPrice: 220,
      price: 180,
      rating: 5,
      reviewsCount: 55,
      outOfStock: true,
    },
       {
      id: 13,
      category: 'CRYSTAL GLEAM',
      name: 'Diamond Dust Setting Powder',
      image: 'assets/imgs/product-img-1.png',
      oldPrice: 220,
      price: 180,
      rating: 5,
      reviewsCount: 55,
      outOfStock: true,
    },

       {
      id: 14,
      category: 'CRYSTAL GLEAM',
      name: 'Diamond Dust Setting Powder',
      image: 'assets/imgs/product-img-1.png',
      oldPrice: 220,
      price: 180,
      rating: 5,
      reviewsCount: 55,
      outOfStock: true,
    },

       {
      id: 15,
      category: 'CRYSTAL GLEAM',
      name: 'Diamond Dust Setting Powder',
      image: 'assets/imgs/product-img-1.png',
      oldPrice: 220,
      price: 180,
      rating: 5,
      reviewsCount: 55,
      outOfStock: true,
    },

       {
      id: 16,
      category: 'CRYSTAL GLEAM',
      name: 'Diamond Dust Setting Powder',
      image: 'assets/imgs/product-img-1.png',
      oldPrice: 220,
      price: 180,
      rating: 5,
      reviewsCount: 55,
      outOfStock: true,
    },

       {
      id: 17,
      category: 'CRYSTAL GLEAM',
      name: 'Diamond Dust Setting Powder',
      image: 'assets/imgs/product-img-1.png',
      oldPrice: 220,
      price: 180,
      rating: 5,
      reviewsCount: 55,
      outOfStock: true,
    },

       {
      id: 18,
      category: 'CRYSTAL GLEAM',
      name: 'Diamond Dust Setting Powder',
      image: 'assets/imgs/product-img-1.png',
      oldPrice: 220,
      price: 180,
      rating: 5,
      reviewsCount: 55,
      outOfStock: true,
    },
  ];

  getAll(): Product[] {
    return this.products;
  }

  getById(id: number): Product | undefined {
    return this.products.find((p) => p.id === id);
  }

  getCategories(): string[] {
    return [...new Set(this.products.map((p) => p.category))];
  }
}
